# Generated by Django 5.0.2 on 2024-06-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineraccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='traineraccount',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='TrainerAccount',
        ),
    ]
