# Generated by Django 5.0.2 on 2024-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exercises',
            field=models.JSONField(default=dict),
        ),
    ]
