# Generated by Django 5.0.4 on 2024-05-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
    ]
