# Generated by Django 5.0.2 on 2024-06-04 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='ali', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='alavi', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='marital_status',
            field=models.BooleanField(choices=[(True, 'Married'), (False, 'Not Married')], default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
        ),
    ]
