# Generated by Django 5.0.2 on 2024-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_birth_date_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='abdomen',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='arm',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='chest',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='height',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='account',
            name='hip',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='leg',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='shoulder',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='thigh',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='waist',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='account',
            name='weight',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='marital_status',
            field=models.BooleanField(choices=[(True, 'Married'), (False, 'Single')], default=False),
        ),
    ]
