# Generated by Django 5.0.2 on 2024-06-06 15:48

import datetime
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_abdomen_account_arm_account_chest_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='abdomen',
        ),
        migrations.RemoveField(
            model_name='account',
            name='arm',
        ),
        migrations.RemoveField(
            model_name='account',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='account',
            name='height',
        ),
        migrations.RemoveField(
            model_name='account',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='account',
            name='leg',
        ),
        migrations.RemoveField(
            model_name='account',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='account',
            name='shoulder',
        ),
        migrations.RemoveField(
            model_name='account',
            name='thigh',
        ),
        migrations.RemoveField(
            model_name='account',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='account',
            name='weight',
        ),
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='AccountInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='ali', max_length=100)),
                ('last_name', models.CharField(default='alavi', max_length=100)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('sex', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True)),
                ('marital_status', models.BooleanField(choices=[(True, 'Married'), (False, 'Single')], default=False)),
                ('weight', models.PositiveSmallIntegerField(default=40)),
                ('height', models.FloatField(default=1.5)),
                ('waist', models.FloatField(default=20)),
                ('abdomen', models.FloatField(default=20)),
                ('chest', models.FloatField(default=20)),
                ('leg', models.FloatField(default=20)),
                ('arm', models.FloatField(default=20)),
                ('hip', models.FloatField(default=20)),
                ('thigh', models.FloatField(default=20)),
                ('shoulder', models.FloatField(default=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
