# Generated by Django 5.0.2 on 2024-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_traineraccount_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineraccount',
            name='city',
            field=models.CharField(choices=[('1', 'تهران'), ('2', 'گیلان'), ('3', 'آذربایجان شرقی'), ('4', 'خوزستان'), ('5', 'فارس'), ('6', 'اصفهان'), ('7', 'خراسان رضوی'), ('8', 'قزوین'), ('9', 'سمنان'), ('10', 'قم'), ('11', 'مرکزی'), ('12', 'زنجان'), ('13', 'مازندران'), ('14', 'گلستان'), ('15', 'اردبیل'), ('16', 'آذربایجان غربی'), ('17', 'همدان'), ('18', 'کرمانشاه'), ('19', 'ایلام'), ('20', 'کهگیلویه و بویراحمد'), ('21', 'بوشهر'), ('22', 'زاهدان'), ('23', 'هرمزگان'), ('24', 'مرکزی')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
