# Generated by Django 5.0.2 on 2024-07-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
