# Generated by Django 5.0.2 on 2024-06-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_options_alter_account_managers_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='AthleteAccount',
        ),
    ]
