# Generated by Django 5.0.2 on 2024-06-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_athleteaccount_traineraccount_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerAccount',
        ),
    ]
