# Generated by Django 5.0.2 on 2024-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_athleteaccount_groups_and_more'),
        ('admin', '0005_alter_logentry_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AthleteAccount',
            new_name='Account',
        ),
    ]
