# Generated by Django 5.0.2 on 2024-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_traineraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineraccount',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='traineraccount',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='traineraccount',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='traineraccount',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='traineraccount',
            name='sex',
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
