# Generated by Django 5.0.2 on 2024-06-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_traineraccount_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Athlete'},
        ),
        migrations.AlterModelOptions(
            name='traineraccount',
            options={'verbose_name': 'Trainer'},
        ),
    ]
